version: '3.7'
services:
  server:
    build:
      context: ./../
      args:
        extras: server
      dockerfile: ./docker/Dockerfile
    tty: true
    container_name: nerddiary-server
    command: nerddiary --log-level DEBUG --log-file /app/log/server.log server -p 80 -r
    volumes:
      - ./../devplayground/:/app/log
      - ./../devplayground/:/app/data
      - ./../nerddiary:/app/nerddiary
    ports:
      - 8880:80
