import enum


@enum.unique
class RPCErrors(enum.IntEnum):
    SESSION_NOT_FOUND = -1
    SESSION_INCORRECT_STATUS = -10
    SESSION_INCORRECT_PASSWORD_OR_KEY = -20
    ERROR_GETTING_SESSION = -1001
    ERROR_POLL_NOT_FOUND = -2001
    ERROR_PARSE_ERROR = -32700
    ERROR_INVALID_REQUEST = -32600
    ERROR_METHOD_NOT_FOUND = -32601
    ERROR_INVALID_PARAMS = -32602
    ERROR_INTERNAL_ERROR = -32603
    ERROR_SERVER_ERROR = -32000
