import enum

from jsonrpcserver.codes import (
    ERROR_INTERNAL_ERROR,
    ERROR_INVALID_PARAMS,
    ERROR_INVALID_REQUEST,
    ERROR_METHOD_NOT_FOUND,
    ERROR_PARSE_ERROR,
    ERROR_SERVER_ERROR,
)


@enum.unique
class RPCErrors(enum.IntEnum):
    SESSION_NOT_FOUND = -1
    SESSION_INCORRECT_STATUS = -10
    SESSION_INCORRECT_PASSWORD_OR_KEY = -20
    ERROR_GETTING_SESSION = -1001
    ERROR_INVALID_PARAMS = ERROR_INVALID_PARAMS
    ERROR_INTERNAL_ERROR = ERROR_INTERNAL_ERROR
    ERROR_METHOD_NOT_FOUND = ERROR_METHOD_NOT_FOUND
    ERROR_INVALID_REQUEST = ERROR_INVALID_REQUEST
    ERROR_PARSE_ERROR = ERROR_PARSE_ERROR
    ERROR_SERVER_ERROR = ERROR_SERVER_ERROR
